name: incm
description: "INCM Real Estate Application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  rush:
    git:
      url: https://github.com/khaledSayedAbdellah/rush
      ref: "2ff9fce"
  fast_http: ^1.0.6
  go_router: ^7.1.1
  provider: ^6.0.5
  get_it: ^7.6.0
  shared_preferences: ^2.1.1
  photo_view: ^0.14.0
  flutter_screenutil: ^5.7.0
  state_extended: ^5.5.0
  equatable: ^2.0.5
  internet_connection_checker_plus: ^2.0.0
  dartz: ^0.10.1
  http: ^1.0.0
  flutter_svg: ^2.0.5
  intl: ^0.20.2
  google_fonts: ^5.1.0
  flutter_launcher_icons: ^0.14.4
  gap: ^3.0.1
  visibility_detector: ^0.4.0+2
  fluttertoast: ^8.2.4
  url_launcher: ^6.3.2
  video_player: ^2.8.2
  dio: ^5.3.3
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  file_picker: ^8.0.0
  file_selector: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - i18n/
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/logos/consultation/
    - assets/logos/facility/
    - assets/logos/franchise/
    - assets/logos/marketing/
    - assets/logos/primary/
    - assets/logos/retail/
    - assets/fonts/
    - assets/videos/

  fonts:
    - family: AloeveraDisplay
      fonts:
        - asset: assets/fonts/AloeveraDisplay-SemiBold.ttf
          weight: 600
    - family: Optimal
      fonts:
        - asset: assets/fonts/Optimal.ttf
          weight: 400

    - family: OptimalBold
      fonts:
        - asset: assets/fonts/OptimalBold.ttf
          weight: 400
    - family: AloeveraDisplaySemiBold
      fonts:
        - asset: assets/fonts/AloeveraDisplaySemiBold.ttf
          weight: 400
    - family: AloeveraDisplayRegular
      fonts:
        - asset: assets/fonts/AloeveraDisplayRegular.ttf
          weight: 400
    - family: AloeveraDisplayBold
      fonts:
        - asset: assets/fonts/AloeveraDisplayBold.ttf
          weight: 400





flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/logos/INCM.png"
  adaptive_icon_background: "#F4ED47"
  adaptive_icon_foreground: "assets/logos/INCM.png"
  remove_alpha_ios: true
